name: Upload to TestFlight

on:  
  workflow_dispatch  # Permet de lancer manuellement l'action depuis GitHub

jobs:
  upload:
    runs-on: macos-latest  # Utilisation d’un Mac gratuit sur GitHub Actions
    steps:
      - name: 📥 Cloner le dépôt
        uses: actions/checkout@v3

      - name: 🔧 Installer Fastlane
        run: gem install fastlane  # Fastlane est un outil pour l’App Store

      - name: 🚀 Envoyer le build sur TestFlight
        env:
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          BUNDLE_ID: ${{ secrets.BUNDLE_ID }}
          APP_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
        run: |
          fastlane deliver --ipa "chemin-vers-ton-fichier.ipa" \
            --username "$APPLE_ID" \
            --app_identifier "$BUNDLE_ID" \
            --team_id "$APPLE_TEAM_ID" \
            --skip_metadata \
            --skip_screenshots \
            --automatic_release
